# Generated by Django 3.1.1 on 2020-09-14 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nota',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
