# Generated by Django 3.1.1 on 2020-09-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='id_usuario',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
